export const GET_ORDER_LIST = "GET_ORDER_LIST"

export const GET_DEFAULT_ADDRESS = "GET_DEFAULT_ADDRESS"
export const GET_ADDRESS = "GET_ADDRESS"

export const DEL_PREPARE_ORDER = 'DEL_PREPARE_ORDER'
export const PREPARE_ORDER = "PREPARE_ORDER"